### ISSUE TITLE
More Bucket Info

### ISSUE THREAD

**Issue by GoodLucky777** [PetteriM1/LoggerX#1]
This plugin logs filling and emptying buckets. But the biggest problem is it doesn't log what you fill or empty. For example, lava or water. Can you add feature that also log what liquid the player fill or empty it?

**Comment by PetteriM1** [comment]
Ok

**Comment by GoodLucky777** [comment]
Thank you!

**Comment by PetteriM1** [comment]
Fixed in cef4aa1
